### PR TITLE
Speech to text module #36

### PR DESCRIPTION
**Pull request by Oviyabalamurugan**
1.Video uploaded in VideoDemo.mp4 file
2.Speech to Text converter code in Speech_To_Text.ipynb
3.Video file converted to audio file saved as AudioConverted.wav file
4.Audio file converted as text file saved as transcription.txt. It is the final output required.
5.Listed all packages used in requirement.txt file.

### CODE REVIEW

**Comment by GrayFlash** [comment]
@Oviyabalamurugan Your PS seems valid to me, and I will be probably merging it for the moment, but it will be great if you can use any SpeechRecognition module that locally converts speech-to-text. The SpeechRecognition module uses Google API and sends requests with the audio and waits for the text. The purpose to divide the audio by 60 was to avoid the timeout for the same. Since you have made it so far, it will be great if the code to upgrade it will come from your end.

Thank You!!

**Review by GrayFlash — COMMENTED** [review]
Delete the .wav and.mp4 files and make the commit, I don't want to unnecessarily increase the size of the repository.

**Comment by Oviyabalamurugan** [comment]
Deleted the .wav and.mp4 files and made the commit.

**Comment by Oviyabalamurugan** [comment]
> @Oviyabalamurugan Your PS seems valid to me, and I will be probably merging it for the moment, but it will be great if you can use any SpeechRecognition module that locally converts speech-to-text. The SpeechRecognition module uses Google API and sends requests with the audio and waits for the text. The purpose to divide the audio by 60 was to avoid the timeout for the same. Since you have made it so far, it will be great if the code to upgrade it will come from your end.
> 
> Thank You!!

Sure Will do the changes such that it will have a  local conversion.But I need some time 4 to 5 days for it.

**Review by GrayFlash — APPROVED** [review]

**Comment by GrayFlash** [comment]
> Sure Will do the changes such that it will have a local conversion.But I need some time 4 to 5 days for it.

That's fine, it will be great if you create an issue for the same and I'll add level3 tags and assign you.

**Comment by Oviyabalamurugan** [comment]
> > Sure Will do the changes such that it will have a local conversion.But I need some time 4 to 5 days for it.
> 
> That's fine, it will be great if you create an issue for the same and I'll add level3 tags and assign you.

sure will do.

**Pull request merged**
