### PR TITLE
Added: update requirements.txt #issue-1 fixed

### LINKED ISSUE #1: Update Requirements.txt
Go through the python codes in the main branch and find out which libraries are used in this project. Create requirements.txt in the GSSoC21 branch and list them out in it.

### PR DESCRIPTION
**Pull request by balarka135**
1. added requirments.txt, issue #1  fixed

### CODE REVIEW

**Comment by GrayFlash** [comment]
@balarka135 you have pushed an empty file.

**Comment by balarka135** [comment]
fixed issue 1, check it again

**Review by Anshoo-Rajput — COMMENTED** [review]
@balarka135 requirements.txt that you have pushed is empty. You have to add the list of libraries include in the source codes in alphabetical order. For an example it should look something like this:
pip==21.0.1
python==3.8.6
package==version

**Comment by balarka135** [comment]
@D3ADSH0T25 I have a Doubt, in your comment, you mentioned that I have to add the libraries include in the source code. But, there is no source code in the file of the EduHelp repository.

Or I have to add the libraries that is required for this EduHelp project in the requirements.txt

**Comment by Anshoo-Rajput** [comment]
> @D3ADSH0T25 I have a Doubt, in your comment, you mentioned that I have to add the libraries include in the source code. But, there is no source code in the file of the EduHelp repository.
> 
> Or I have to add the libraries that is required for this EduHelp project in the requirements.txt

@balarka135 yes this branch is clean as of now for contribution purposes you can check all the work by switching to the main branch
image

**Comment by balarka135** [comment]
@D3ADSH0T25 
I have to add those libraries in requirement's.txt that are available in the main branch?

**Comment by Anshoo-Rajput** [comment]
yes, the libraries that are used in python codes.

**Comment by balarka135** [comment]
@D3ADSH0T25 
I committed requirements.txt as you said earlier. check it,
Screenshot (2)

**Comment by GrayFlash** [comment]
> @D3ADSH0T25
> I committed requirements.txt as you said earlier. check it,

Can you tell us the steps you followed for making the commit and creating pr? @balarka135

**Comment by balarka135** [comment]
1. git add .
2. git commit -m "update requirements fixed"
3. git push origin issue-1  (issue-1 is my branch);

when I first committed to this repository, I saw the pull request option and pulled it
but I didn't see any PR option in the next commits I did. 
and why the empty file was shown I don't know. Because I pushed the file that includes the libraries. Thank you
@GrayFlash @D3ADSH0T25

**Comment by GrayFlash** [comment]
Great Job @balarka135 !! Actually you commited on a different branch and hence we could not see the file as we were on gssoc21 branch. Issue has been resolved.

**Comment by balarka135** [comment]
@GrayFlash Sorry for my mistakes. Thank you for merging.

**Pull request merged**
