### PR TITLE
Improving Footer 

### PR DESCRIPTION
**Pull request by arpit456jain**
Previous Footer
previous footer

New Footer
footer in Desk top

**Fully Responsive in small screens**

https://user-images.githubusercontent.com/55352601/116810342-e4df9480-ab60-11eb-9ba6-343cdc1aa905.mp4

Fixes:#90

### CODE REVIEW

**Comment by arpit456jain** [comment]
@shankhanil007 kindly review my PR and give it suitable label (if possible level3 as it takes a lot time to make it responsive)

I can make a separate issue for making it responsive but i thought it will save time of yours and mine too

**Comment by shankhanil007** [comment]
@arpit456jain I really appreciate the efforts that you have put in. I can see that you have written a substantial amount of code to improve the footer. Surely, you deserve level3 points.

Also, I feel you can make a separate issue for making it responsive because this PR is beyond the scope of level3.

**Comment by arpit456jain** [comment]
@shankhanil007 thank a lot ..

Although I have made the footer responsive in this PR but there are some work left like adding link in footer to various section on page and some minor details .
if you think I had worked more than enough under this PR kindly give level3 to my that PR. .

**Comment by shankhanil007** [comment]
Sure!

**Pull request merged**
