### PR TITLE
[Gssoc'21] Enhace the index.html

### LINKED ISSUE #53: [Gssoc'21] Enhancement in index.html
I would like to make some enhancement on index.html

### PR DESCRIPTION
**Pull request by arpit456jain**
1.The contact form is not in center and the. Text is not visible i make it visible and responsive
2.Social media icons are static i make them dynamic and add animation to them
3.Text was very big in mobile view i write some media queries for it.
4.text in navbar is not visible its black i make them white

fix : #53 

https://user-images.githubusercontent.com/55352601/115123330-278a6400-9fda-11eb-9407-1bdcdfbf06b2.mp4

### CODE REVIEW

**Comment by arpit456jain** [comment]
@D3ADSH0T25 i had tried to make team section responsive but its taking a long time then expecting so i have to design a new section , I will create a new PR for this.

kindy review my PR and add labels to it before merging

**Comment by arpit456jain** [comment]
@shankhanil007 give me Just 1 min i can resolve this conflict just 1 min

**Comment by shankhanil007** [comment]
Okay cool

**Comment by arpit456jain** [comment]
@shankhanil007 its done kindly add appropriate labels before merging

**Pull request merged**
