### PR TITLE
Added python script inorder to calculate the difference between two arrays of pixel values, i.e., two images.

### PR DESCRIPTION
**Pull request by anandhu-eng**
The sample images used for the comparison is named as sample1.PNG and sample2.PNG which are shown below.
sample1:
sample1

sample2:
sample2

the output of the code:
Screenshot from 2021-03-20 01-40-16

In the beginning, the sample1 is compared to itself that yields 100 percent similarity.
Secondly, the sample 1 is compared to sample 2 which yields 93.8610 percent similarity.

NOTE: The option to compare two images of different sizes are not provided in the code as the size of the images of screen taken     during recording doesn't change.

### CODE REVIEW

**Comment by anandhu-eng** [comment]
Do suggest should i include the code to resize the two images and compare each other (useful for comparing the images of different dimensions).
I haven't added that here because the main purpose of the code block would be to compare the two images while recording, which obviously wont be of different dimensions as the screen area of recording would be fixed by the user at the beginning.

**Comment by GrayFlash** [comment]
@anandhu-eng for this point it seems fine to me, but we will have to see if it is accurate at later stage.

**Comment by GrayFlash** [comment]
@anandhu-eng move the py file to a folder named ```utils``` and delete the sample images and the text pertaining to them... I merged without noticing that, create a new PR, I don't wish to revert

**Comment by anandhu-eng** [comment]
ok sure will be done asap!

**Pull request merged**
