### PR TITLE
Website for screenshot taker added

### LINKED ISSUE #2: Website for Screenshot Taker
Make a simple website for the screenshot taker product. There should be a home page comprising of the product description, photos of the developers and project video. For details of the product, one can refer to the README file in the main branch.

### PR DESCRIPTION
**Pull request by Subhangini**
Fixes #2

### CODE REVIEW

**Comment by shankhanil007** [comment]
@Subhangini please add a short video or screenshots of your website so that we can review your work easily.

**Comment by Subhangini** [comment]
https://subhangini.github.io/EduHelp/
this is the link for the website

**Comment by shankhanil007** [comment]
Good work! We will create more issues related to improving the website in the upcoming days.

**Comment by Subhangini** [comment]
> Good work! We will create more issues related to improving the website in the upcoming days.

Thank you. Waiting to grab them🙂

**Pull request merged**
