### PR TITLE
new Contact us section

### LINKED ISSUE #64: New and Better Contact section on a new page
I would like to add New and Better Contact section on a new page current contact section is very dull

### PR DESCRIPTION
**Pull request by arpit456jain**
new Contact us section

https://user-images.githubusercontent.com/55352601/115168179-a74a2880-a0d7-11eb-8e78-574e8e1df57b.mp4

fixes : #64

### CODE REVIEW

**Comment by arpit456jain** [comment]
@shankhanil007 i have removed the previous contact us section and its related CSS
kindly review this PR and add the suitable label to it before merging

**Comment by arpit456jain** [comment]
edu

**Comment by shankhanil007** [comment]
Change the color of the contact us section on the home page. Change it to a light color. The Blue one is too eye catchy. Make a new PR for it

**Comment by arpit456jain** [comment]
> Change the color of the contact us section on the home page. Change it to a light color. The Blue one is too eye catchy. Make a new PR for it

Ok

**Comment by arpit456jain** [comment]
> Change the color of the contact us section on the home page. Change it to a light color. The Blue one is too eye catchy. Make a new PR for it

@shankhanil007  contact us section on home page ?? you mean footer on home page?

**Comment by shankhanil007** [comment]
Yah

**Pull request merged**
