### PR TITLE
Provided UI enhancement 

### PR DESCRIPTION
**Pull request by anandhu-eng**
Previously, the user had to clear the text in the entry box in order to enter the name of the file to be saved.

Now it has been made simple and more convenient to the user. The user now only need to click the entry box at the first time in order to write the name of the output file to be saved.

### CODE REVIEW

**Comment by GrayFlash** [comment]
@anandhu-eng it's a good pr and deserves to be merged, but the problem is we have not made a UI in our GSSoC21 branch. But I am glad at least someone started working on the .py scripts. 
It will be great if you implement the utils files before going on to UI, refer issues #10 #9  these can be implemented after refering the codes in main branch, and I am hopefull you will be able to do those.

**Comment by GrayFlash** [comment]
Also refer to [this](https://docs.google.com/document/d/1NgP7kcJPSz0XaIq51hJkgtHk4Pm7J58N76-_0py2DTc/edit) doc, to see clear ideas about the implementation.

**Comment by anandhu-eng** [comment]
Ok sure:)

**Comment by anandhu-eng** [comment]
will it be able to merge if i fix a bug in the reference code which does not belong to UI?....just figured a problem in the code

**Comment by GrayFlash** [comment]
Actually, we were not sure if we wish to keep the UI in Tkinter, we are looking forward to making a desktop app out of it later and hence we ourselves are looking into it. For this moment it will be great if you can work on the utils part, we are hopeful you will bring a lot of fruitful contribution over there as well. For instance, you can make a py file that can calculate the difference between two arrays of pixel values, i.e., two images.

**Comment by anandhu-eng** [comment]
ok let me work on that:)

**Pull request closed without merging**
