### PR TITLE
[Gssoc'21] Responsive Navbar 

### PR DESCRIPTION
**Pull request by arpit456jain**
https://user-images.githubusercontent.com/55352601/115135973-428cc080-a03a-11eb-817b-79c5de080735.mp4

### CODE REVIEW

**Comment by arpit456jain** [comment]
@shankhanil007 kindly review my PR and suitable labels to it as i have to remove all the previous navbar CSS and write some new CSS for this navbar

**Comment by arpit456jain** [comment]
@shankhanil007 kindly give it  a **level 3** i had also made the team section responsive and it is looking 10 times better than previous uploading the video and making the commit

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/115136533-ef1c7180-a03d-11eb-80f1-cd784cdd3d42.mp4

**Comment by shankhanil007** [comment]
Great Work! It's looking really great.

**Pull request merged**
